version: "3.9"
services:
  server:
    container_name: ycal-api-v0-production-server
    build:
      context: .
      dockerfile: production.dockerfile
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - SCREENSHOT=true
  doc:
    container_name: ycal-api-v0-doc
    build:
      context: .
      dockerfile: openapi/v0/Dockerfile
    ports:
      - 18080:18080
    volumes:
      - ./openapi/v0:/spec
    command: preview-docs --port=18080 --host=0.0.0.0 openapi.yaml
  redoc:
    build:
      context: .
      dockerfile: doc/redoc.dockerfile
    volumes:
      - .:/redoc
    command: redoc-cli build openapi/v0/openapi.yaml -o doc/index.html
