version: "3.9"
services:
  doc:
    container_name: ycal-api-v0-doc
    build:
      context: .
      dockerfile: openapi/v0/Dockerfile
    ports:
      - 18080:18080
    command: preview-docs --port=18080 --host=0.0.0.0 openapi.yaml
  redoc:
    volumes:
      - ./doc:/doc
    build:
      context: .
      dockerfile: doc/redoc.dockerfile
    command: redoc-cli bundle openapi.yaml -o doc/index.html
