openapi: 3.0.3
info:
  title: Yahoo! Calendar API
  version: v0
servers:
  - url: http://localhost:8080/api/v0
    description: local server
paths:
  /:
    get:
      summary: API Information
      responses:
        "200":
          description: >
            エンドポイントの情報を返します。
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to Yahoo! Calendar API
  /sessions/new:
    get:
      summary: Login to Yahoo!
      responses:
        "200":
          description: Yahoo! に SMS 認証またはメール認証でログインするためのパスです。Yahoo! Calendar API と クライアントを WebSocket でつなぎます。
  /events/export:
    get:
      summary: Export iCalendar
      responses:
        "200":
          description: iCalendar 形式の ics ファイルをテキスト形式で返します。
