name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.20.1"
      - name: Setup
        uses: actions/checkout@v3
      - name: Check code format
        run: deno fmt --check
      - name: Run test
        run: docker compose run server deno test -A --unstable
